backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: /static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-post"}
      - {label: "Background Color", name: "color", widget: "color"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        allow_add: true
        label_singular: "image"
        fields: [
          {label: "Image", name: "image", widget: "image", media_folder: "img/work"}
        ]
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Site Title", name: "title", widget: "string", default: "jetzt-immer-studio"}
          - {label: "Site Description", name: "description", widget: "string", default: "jetzt-immer-studio"}
          - {label: "Image", name: "image", widget: "image"}
      - file: "src/pages/info/index.md"
        label: "Info Page"
        name: "info"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "image", name: "image", widget: "image"}
          - {label: "Address", name: "address", widget: "markdown", default: ""}
          - {label: "Contact", name: "contact", widget: "markdown", default: ""}
          - {label: "Social", name: "social", widget: "markdown", default: ""}
          - {label: "About", name: "about", widget: "markdown", default: ""}
          - {label: "CV", name: "cv", widget: "markdown", default: ""}
          - {label: "Imprint", name: "imprint", widget: "markdown", default: ""}
          - {label: "Developer", name: "developer", widget: "markdown", default: "John SH Lee"}
          - {label: "Copyright", name: "copyright", widget: "markdown", default: "jetzt-immer-studio"}
